import { useEffect, useState } from 'react';
import { Users, UserPlus, UserCheck, Moon, UserX, RefreshCcw, LockKeyhole } from 'lucide-react';
import { Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import AppSidebar from './AppSidebar';
import PeriodSelector from './PeriodSelector';
import { getCasaMargotClients } from '../services/api';
const COLORS=['#4d9661','#d9b27f','#c7ced6','#203b5c'];
const money=(n=0)=>new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN',maximumFractionDigits:0}).format(Number(n)||0);const pct=(n=0)=>`${Math.round((Number(n)||0)*10)/10}%`;
const fallback={period:{label:'Periodo'},periodOptions:{years:[2026]},kpis:{},statusBreakdown:[],acquisition:[],topClients:[],clients:[],sellerPortfolio:[],unavailable:[]};
function Empty({title,text}){return <div className="unavailableState"><LockKeyhole size={22}/><div><b>{title}</b><p>{text}</p></div><span>Dato por activar</span></div>}
function Kpi({icon:Icon,title,value,helper}){return <article className="secondaryKpi"><span><Icon size={22}/></span><div><small>{title}</small><b>{value}</b><p>{helper}</p></div></article>}
export default function ClientesScreen(){const now=new Date();const [period,setPeriod]=useState({type:'month',index:now.getMonth()+1,year:now.getFullYear()});const [data,setData]=useState(fallback);const [loading,setLoading]=useState(true);useEffect(()=>{setLoading(true);getCasaMargotClients(period).then(setData).catch(e=>{console.error(e);setData(fallback)}).finally(()=>setLoading(false))},[period.type,period.index,period.year]);const years=data.periodOptions?.years?.length?data.periodOptions.years:[period.year];return <main className="appShell"><AppSidebar/><div className="dashboard secondaryDashboard">
<header className="topbar"><div><p className="eyebrow">Casa Margot · Inteligencia de clientes</p><h1>Clientes</h1><p>Altas, actividad, dormancia, recompra y valor comercial por cliente. {loading?'Actualizando datos…':''}</p></div><PeriodSelector {...period} label={data.period?.label} years={years} onChange={setPeriod}/></header>
<div className="secondaryKpiGrid"><Kpi icon={Users} title="Clientes registrados" value={data.kpis?.totalClients||0} helper="Base conocida"/><Kpi icon={UserPlus} title="Clientes nuevos" value={data.kpis?.newClients||0} helper="Fecha de alta dentro del periodo"/><Kpi icon={UserCheck} title="Activos" value={data.kpis?.activeClients||0} helper="Compra en últimos 2 meses"/><Kpi icon={Moon} title="Dormidos" value={data.kpis?.dormantClients||0} helper="2–6 meses sin comprar"/><Kpi icon={UserX} title="Inactivos" value={data.kpis?.inactiveClients||0} helper="6+ meses sin comprar"/><Kpi icon={RefreshCcw} title="Recompra" value={pct(data.kpis?.repurchaseRate)} helper={`${data.kpis?.repurchaseClients||0} clientes con recompra`}/></div>
<div className="secondaryGrid">
<section className="panel"><div className="panelTitle"><div><h3>Estado de la cartera</h3><p>Situación inferida a la fecha final del periodo.</p></div></div><div className="chartFrame"><ResponsiveContainer width="100%" height="100%" minWidth={1} minHeight={1}><PieChart><Pie data={data.statusBreakdown||[]} dataKey="value" nameKey="name" innerRadius="38%" outerRadius="64%">{(data.statusBreakdown||[]).map((_,i)=><Cell key={i} fill={COLORS[i%COLORS.length]}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer></div><div className="statusLegend">{(data.statusBreakdown||[]).map((x,i)=><span key={x.name}><i style={{background:COLORS[i%COLORS.length]}}/>{x.name}<b>{x.value}</b></span>)}</div></section>
<section className="panel"><div className="panelTitle"><div><h3>Altas por mes</h3><p>Cuándo se incorporaron nuevos clientes durante {period.year}.</p></div></div><div className="chartFrame chartFrameTall"><ResponsiveContainer width="100%" height="100%" minWidth={1} minHeight={1}><BarChart data={data.acquisition||[]} margin={{top:8,right:8,bottom:8,left:-8}}><CartesianGrid vertical={false} strokeDasharray="4 6"/><XAxis dataKey="month"/><YAxis allowDecimals={false}/><Tooltip/><Bar dataKey="clients" name="Clientes nuevos" fill="#4d9661" radius={[7,7,0,0]}/></BarChart></ResponsiveContainer></div></section>
<section className="panel secondaryWide"><div className="panelTitle"><div><h3>Clientes con mayor actividad comercial</h3><p>Venta, compras y ticket dentro del periodo seleccionado.</p></div></div><div className="dataTable"><div className="dataRow clientHead"><span>Cliente</span><span>Estado</span><span>Venta</span><span>Compras</span><span>Ticket</span><span>Vendedor</span></div>{(data.topClients||[]).map(x=><div className="dataRow clientHead" key={x.id}><b>{x.name}</b><span className={`statusPill ${x.status==='Activo'?'active':x.status==='Dormido'?'sleep':'inactive'}`}>{x.status}</span><span>{money(x.periodRevenue)}</span><span>{x.periodSales}</span><span>{money(x.periodTicket)}</span><span>{x.seller}</span></div>)}</div></section>
<section className="panel"><div className="panelTitle"><div><h3>Cartera por vendedor</h3><p>Clientes asignados y venta generada en el periodo.</p></div></div><div className="rankSimple">{(data.sellerPortfolio||[]).slice(0,8).map(x=><article key={x.name}><div><b>{x.name}</b><small>{x.active} activos de {x.clients}</small></div><strong>{money(x.revenue)}</strong></article>)}</div></section>
<section className="panel"><div className="panelTitle"><div><h3>Perfil y origen</h3><p>Información que enriquecerá el entendimiento del cliente.</p></div></div><div className="activationList">{(data.unavailable||[]).map(x=><Empty key={x.key} title={x.title} text={x.message}/>)}</div></section>
<section className="panel secondaryWide"><div className="panelTitle"><div><h3>Base completa de clientes</h3><p>Estado inferido y última actividad de compra.</p></div></div><div className="catalogTableWrap"><table className="catalogTable"><thead><tr><th>Cliente</th><th>Alta</th><th>Estado</th><th>Vendedor</th><th>Venta periodo</th><th>Compras periodo</th><th>Venta histórica</th><th>Última compra</th></tr></thead><tbody>{(data.clients||[]).map(x=><tr key={x.id}><td><b>{x.name}</b><small>{x.id}</small></td><td>{x.joinDate?new Date(x.joinDate).toLocaleDateString('es-MX'):'—'}</td><td><span className={`statusPill ${x.status==='Activo'?'active':x.status==='Dormido'?'sleep':'inactive'}`}>{x.status}</span></td><td>{x.seller}</td><td>{money(x.periodRevenue)}</td><td>{x.periodSales}</td><td>{money(x.lifetimeRevenue)}</td><td>{x.lastPurchase?new Date(x.lastPurchase).toLocaleDateString('es-MX'):'Sin compra'}</td></tr>)}</tbody></table></div></section>
</div></div></main>}




// ----> LAST FUNCTIONAL AUG27/26 <-----



// import { useEffect, useState } from 'react';
// import { Users, UserPlus, UserCheck, Moon, UserX, RefreshCcw, LockKeyhole } from 'lucide-react';
// import { Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
// import AppSidebar from './AppSidebar';
// import PeriodSelector from './PeriodSelector';
// import { getCasaMargotClients } from '../services/api';
// const COLORS=['#4d9661','#d9b27f','#c7ced6','#203b5c'];
// const money=(n=0)=>new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN',maximumFractionDigits:0}).format(Number(n)||0);const pct=(n=0)=>`${Math.round((Number(n)||0)*10)/10}%`;
// const fallback={period:{label:'Periodo'},periodOptions:{years:[2026]},kpis:{},statusBreakdown:[],acquisition:[],topClients:[],clients:[],sellerPortfolio:[],unavailable:[]};
// function Empty({title,text}){return <div className="unavailableState"><LockKeyhole size={22}/><div><b>{title}</b><p>{text}</p></div><span>Dato por activar</span></div>}
// function Kpi({icon:Icon,title,value,helper}){return <article className="secondaryKpi"><span><Icon size={22}/></span><div><small>{title}</small><b>{value}</b><p>{helper}</p></div></article>}
// export default function ClientesScreen(){const now=new Date();const [period,setPeriod]=useState({type:'month',index:now.getMonth()+1,year:now.getFullYear()});const [data,setData]=useState(fallback);const [loading,setLoading]=useState(true);useEffect(()=>{setLoading(true);getCasaMargotClients(period).then(setData).catch(e=>{console.error(e);setData(fallback)}).finally(()=>setLoading(false))},[period.type,period.index,period.year]);const years=data.periodOptions?.years?.length?data.periodOptions.years:[period.year];return <main className="appShell"><AppSidebar/><div className="dashboard secondaryDashboard">
// <header className="topbar"><div><p className="eyebrow">Casa Margot · Inteligencia de clientes</p><h1>Clientes</h1><p>Altas, actividad, dormancia, recompra y valor comercial por cliente. {loading?'Actualizando datos…':''}</p></div><PeriodSelector {...period} label={data.period?.label} years={years} onChange={setPeriod}/></header>
// <div className="secondaryKpiGrid"><Kpi icon={Users} title="Clientes registrados" value={data.kpis?.totalClients||0} helper="Base conocida"/><Kpi icon={UserPlus} title="Clientes nuevos" value={data.kpis?.newClients||0} helper="Fecha de alta dentro del periodo"/><Kpi icon={UserCheck} title="Activos" value={data.kpis?.activeClients||0} helper="Compra en últimos 2 meses"/><Kpi icon={Moon} title="Dormidos" value={data.kpis?.dormantClients||0} helper="2–6 meses sin comprar"/><Kpi icon={UserX} title="Inactivos" value={data.kpis?.inactiveClients||0} helper="6+ meses sin comprar"/><Kpi icon={RefreshCcw} title="Recompra" value={pct(data.kpis?.repurchaseRate)} helper={`${data.kpis?.repurchaseClients||0} clientes con recompra`}/></div>
// <div className="secondaryGrid">
// <section className="panel"><div className="panelTitle"><div><h3>Estado de la cartera</h3><p>Situación inferida a la fecha final del periodo.</p></div></div><ResponsiveContainer width="100%" height={280}><PieChart><Pie data={data.statusBreakdown||[]} dataKey="value" nameKey="name" innerRadius={62} outerRadius={92}>{(data.statusBreakdown||[]).map((_,i)=><Cell key={i} fill={COLORS[i%COLORS.length]}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer><div className="statusLegend">{(data.statusBreakdown||[]).map((x,i)=><span key={x.name}><i style={{background:COLORS[i%COLORS.length]}}/>{x.name}<b>{x.value}</b></span>)}</div></section>
// <section className="panel"><div className="panelTitle"><div><h3>Altas por mes</h3><p>Cuándo se incorporaron nuevos clientes durante {period.year}.</p></div></div><ResponsiveContainer width="100%" height={300}><BarChart data={data.acquisition||[]}><CartesianGrid vertical={false} strokeDasharray="4 6"/><XAxis dataKey="month"/><YAxis allowDecimals={false}/><Tooltip/><Bar dataKey="clients" name="Clientes nuevos" fill="#4d9661" radius={[7,7,0,0]}/></BarChart></ResponsiveContainer></section>
// <section className="panel secondaryWide"><div className="panelTitle"><div><h3>Clientes con mayor actividad comercial</h3><p>Venta, compras y ticket dentro del periodo seleccionado.</p></div></div><div className="dataTable"><div className="dataRow clientHead"><span>Cliente</span><span>Estado</span><span>Venta</span><span>Compras</span><span>Ticket</span><span>Vendedor</span></div>{(data.topClients||[]).map(x=><div className="dataRow clientHead" key={x.id}><b>{x.name}</b><span className={`statusPill ${x.status==='Activo'?'active':x.status==='Dormido'?'sleep':'inactive'}`}>{x.status}</span><span>{money(x.periodRevenue)}</span><span>{x.periodSales}</span><span>{money(x.periodTicket)}</span><span>{x.seller}</span></div>)}</div></section>
// <section className="panel"><div className="panelTitle"><div><h3>Cartera por vendedor</h3><p>Clientes asignados y venta generada en el periodo.</p></div></div><div className="rankSimple">{(data.sellerPortfolio||[]).slice(0,8).map(x=><article key={x.name}><div><b>{x.name}</b><small>{x.active} activos de {x.clients}</small></div><strong>{money(x.revenue)}</strong></article>)}</div></section>
// <section className="panel"><div className="panelTitle"><div><h3>Perfil y origen</h3><p>Información que enriquecerá el entendimiento del cliente.</p></div></div><div className="activationList">{(data.unavailable||[]).map(x=><Empty key={x.key} title={x.title} text={x.message}/>)}</div></section>
// <section className="panel secondaryWide"><div className="panelTitle"><div><h3>Base completa de clientes</h3><p>Estado inferido y última actividad de compra.</p></div></div><div className="catalogTableWrap"><table className="catalogTable"><thead><tr><th>Cliente</th><th>Alta</th><th>Estado</th><th>Vendedor</th><th>Venta periodo</th><th>Compras periodo</th><th>Venta histórica</th><th>Última compra</th></tr></thead><tbody>{(data.clients||[]).map(x=><tr key={x.id}><td><b>{x.name}</b><small>{x.id}</small></td><td>{x.joinDate?new Date(x.joinDate).toLocaleDateString('es-MX'):'—'}</td><td><span className={`statusPill ${x.status==='Activo'?'active':x.status==='Dormido'?'sleep':'inactive'}`}>{x.status}</span></td><td>{x.seller}</td><td>{money(x.periodRevenue)}</td><td>{x.periodSales}</td><td>{money(x.lifetimeRevenue)}</td><td>{x.lastPurchase?new Date(x.lastPurchase).toLocaleDateString('es-MX'):'Sin compra'}</td></tr>)}</tbody></table></div></section>
// </div></div></main>}
