import { useEffect, useState } from 'react';
import { AlertTriangle, ArrowDownCircle, ArrowUpCircle, BarChart3, LockKeyhole, ShoppingCart, Target, TrendingUp, Users } from 'lucide-react';
import { Bar, BarChart, CartesianGrid, Cell, ComposedChart, Legend, Line, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import AppSidebar from './AppSidebar';
import PeriodSelector from './PeriodSelector';
import { getCasaMargotSales } from '../services/api';

const COLORS=['#4d9661','#203b5c','#d9cbb8','#c7ced6','#8fa6b2','#9b7c55'];
const money=(n=0)=>new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN',maximumFractionDigits:0}).format(Number(n)||0);const pct=(n=0)=>`${Math.round((Number(n)||0)*10)/10}%`;
const fallback={period:{label:'Periodo'},meta:{years:[2026]},kpis:{},history:[],goalBars:[],categoryBreakdown:[],productBreakdown:[],channelBreakdown:[],sellerBreakdown:[],clientBreakdown:[],seasonality:{},availability:{},insights:[]};
function growthClass(v=0){return Number(v)<0?'negative':'positive'}function growthIcon(v=0){return Number(v)<0?'↓':'↑'}
function SalesKpi({icon:Icon,title,value,change,helper}){return <section className="ventasKpiCard"><div className="ventasKpiIcon"><Icon size={24}/></div><div><p>{title}</p><h2>{value}</h2>{change!==undefined&&change!==null&&<span className={growthClass(change)}>{growthIcon(change)} {pct(Math.abs(change||0))}</span>}{helper&&<small>{helper}</small>}</div></section>}
function SalesPanel({title,subtitle,children,className=''}){return <section className={`ventasPanel ${className}`}><div className="ventasPanelHeader"><div><h3>{title}</h3>{subtitle&&<p>{subtitle}</p>}</div></div>{children}</section>}
function InsightIcon({type}){if(type==='danger')return <ArrowDownCircle size={22}/>;if(type==='success')return <ArrowUpCircle size={22}/>;return <AlertTriangle size={22}/>}
function Locked({title,text}){return <div className="unavailableState"><LockKeyhole size={22}/><div><b>{title}</b><p>{text}</p></div><span>Dato por activar</span></div>}

export default function VentasScreen(){
 const now=new Date();const [period,setPeriod]=useState({type:'month',index:now.getMonth()+1,year:now.getFullYear()});const [data,setData]=useState(fallback);const [loading,setLoading]=useState(true);
 useEffect(()=>{setLoading(true);getCasaMargotSales(period).then(setData).catch(e=>{console.error('[VentasScreen]',e);setData(fallback)}).finally(()=>setLoading(false))},[period.type,period.index,period.year]);
 const years=data.meta?.years?.length?data.meta.years:[period.year];const topCategory=data.seasonality?.topCategory;const topSeller=data.seasonality?.topSeller;
 return <main className="appShell"><AppSidebar/><div className="dashboard ventasDashboard"><header className="topbar ventasTopbar"><div><p className="eyebrow">Casa Margot · Desempeño comercial</p><h1>Ventas</h1><p>Microscopio de ingresos, recurrencia, productos y fuerza comercial. {loading?'Actualizando datos…':''}</p></div><PeriodSelector {...period} label={data.period?.label||data.meta?.selectedMonthLabel} years={years} onChange={setPeriod}/></header>
 <section className="ventasHero"><div><p>Ingreso total del periodo</p><h2>{money(data.kpis?.monthlySales)}</h2><span className={growthClass(data.kpis?.salesGrowth)}>{growthIcon(data.kpis?.salesGrowth)} {pct(Math.abs(data.kpis?.salesGrowth||0))} vs periodo anterior</span></div><div className="ventasHeroMeta"><p>Meta comercial</p>{data.availability?.goals?<><h3>{money(data.kpis?.monthlyGoal)}</h3></>:<Locked title="Meta aún no disponible" text="Cuando Casa Margot registre metas mensuales o por periodo, este bloque mostrará cumplimiento y brecha."/>}</div></section>
 <div className="ventasKpiGrid"><SalesKpi icon={ShoppingCart} title="Número de ventas" value={data.kpis?.transactions||0} change={data.kpis?.transactionGrowth} helper="vs periodo anterior"/><SalesKpi icon={BarChart3} title="Ticket promedio" value={money(data.kpis?.avgTicket)} change={data.kpis?.avgTicketGrowth} helper="vs periodo anterior"/><SalesKpi icon={Users} title="Clientes únicos" value={data.kpis?.uniqueClients||0} helper={`${data.kpis?.newClients||0} nuevos · ${data.kpis?.recurrentClients||0} con recompra`}/><SalesKpi icon={TrendingUp} title="Venta acumulada año" value={money(data.kpis?.ytdSales)} change={data.kpis?.ytdGrowth} helper={`YTD ${period.year}`}/><SalesKpi icon={Target} title="Meta anual" value={data.availability?.goals?money(data.kpis?.annualGoal):'—'} helper={data.availability?.goals?'Seguimiento anual':'Dato por activar'}/></div>
 <div className="ventasGrid">
 <SalesPanel title="Histórico de ventas" subtitle="Evolución mensual y comparación contra el año anterior." className="ventasWidePanel"><div className="chartFrame chartFrameWide"><ResponsiveContainer width="100%" height="100%" minWidth={1} minHeight={1}><ComposedChart data={data.history||[]} margin={{top:8,right:8,bottom:8,left:-4}}><CartesianGrid vertical={false} strokeDasharray="4 6"/><XAxis dataKey="month"/><YAxis tickFormatter={v=>`$${Math.round(v/1000)}k`}/><Tooltip formatter={v=>money(v)}/><Legend/><Bar dataKey="sales" name="Ventas actuales" fill="#4d9661" radius={[8,8,0,0]}/><Line type="monotone" dataKey="lastYear" name="Año anterior" stroke="#aeb8c5" strokeDasharray="7 7" strokeWidth={2}/></ComposedChart></ResponsiveContainer></div></SalesPanel>
 <SalesPanel title="Lectura rápida" subtitle="Temporadas, concentración y señales críticas."><div className="ventasQuickRead"><article><small>Mes más fuerte</small><b>{data.seasonality?.bestMonth||'Sin datos'}</b><p>Mayor ingreso mensual del año seleccionado.</p></article><article><small>Mes más bajo</small><b>{data.seasonality?.weakestMonth||'Sin datos'}</b><p>Periodo con menor ingreso registrado.</p></article><article><small>Categoría líder</small><b>{topCategory?.name||'Sin datos'}</b><p>{topCategory?`${pct(topCategory.share)} del ingreso del periodo.`:'Sin ventas registradas.'}</p></article><article><small>Vendedor líder</small><b>{topSeller?.name||'Sin datos'}</b><p>{topSeller?`${pct(topSeller.share)} del ingreso del periodo.`:'Sin vendedor registrado.'}</p></article></div></SalesPanel>
 <SalesPanel title="Metas y brechas" subtitle="Ventas reales contra objetivo mensual.">{data.availability?.goals?<div className="chartFrame"><ResponsiveContainer width="100%" height="100%" minWidth={1} minHeight={1}><BarChart data={data.goalBars||[]} margin={{top:8,right:8,bottom:8,left:-8}}><CartesianGrid vertical={false} strokeDasharray="4 6"/><XAxis dataKey="month"/><YAxis/><Tooltip/><Bar dataKey="goal" fill="#d9cbb8"/><Bar dataKey="sales" fill="#4d9661"/></BarChart></ResponsiveContainer></div>:<Locked title="Metas comerciales" text="Agrega una tabla de metas por mes/periodo para activar cumplimiento, brecha y avance anual."/>}</SalesPanel>
 <SalesPanel title="Performance transaccional" subtitle="Volumen de ventas y ticket promedio por mes."><div className="chartFrame"><ResponsiveContainer width="100%" height="100%" minWidth={1} minHeight={1}><ComposedChart data={data.history||[]} margin={{top:8,right:8,bottom:8,left:-8}}><CartesianGrid vertical={false} strokeDasharray="4 6"/><XAxis dataKey="month"/><YAxis yAxisId="left"/><YAxis yAxisId="right" orientation="right" tickFormatter={v=>`$${Math.round(v/1000)}k`}/><Tooltip formatter={(v,n)=>n==='Ticket promedio'?money(v):v}/><Legend/><Bar yAxisId="left" dataKey="transactions" name="Ventas" fill="#203b5c" radius={[8,8,0,0]}/><Line yAxisId="right" type="monotone" dataKey="avgTicket" name="Ticket promedio" stroke="#4d9661" strokeWidth={3}/></ComposedChart></ResponsiveContainer></div></SalesPanel>
 <SalesPanel title="Segmentación por producto" subtitle="Qué familias venden más dentro del periodo."><div className="ventasSplitPanel"><div className="chartFrame chartFramePie"><ResponsiveContainer width="100%" height="100%" minWidth={1} minHeight={1}><PieChart><Pie data={data.categoryBreakdown||[]} innerRadius={55} outerRadius={82} dataKey="revenue">{(data.categoryBreakdown||[]).map((_,i)=><Cell key={i} fill={COLORS[i%COLORS.length]}/>)}</Pie><Tooltip formatter={v=>money(v)}/></PieChart></ResponsiveContainer></div><div className="ventasRankList">{(data.categoryBreakdown||[]).map((x,i)=><article key={x.name}><div><b style={{background:COLORS[i%COLORS.length]}}/><span>{x.name}</span></div><strong>{money(x.revenue)}</strong><small>{pct(x.share)} · {x.transactions} ventas · Ticket {money(x.avgTicket)}</small></article>)}</div></div></SalesPanel>
 <SalesPanel title="Segmentación por canal" subtitle="Dónde se origina el ingreso comercial.">{data.availability?.channels?<div className="ventasRankList full">{(data.channelBreakdown||[]).map((x,i)=><article key={x.name}><div><b style={{background:COLORS[i%COLORS.length]}}/><span>{x.name}</span></div><strong>{money(x.revenue)}</strong><div className="ventasProgress"><span style={{width:`${Math.min(x.share||0,100)}%`,background:COLORS[i%COLORS.length]}}/></div><small>{pct(x.share)} · {x.transactions} ventas · Ticket {money(x.avgTicket)}</small></article>)}</div>:<Locked title="Canal de origen" text="MEDIO_ORIGEN todavía no se registra de forma suficiente. Capturarlo activará venta, ticket y clientes por canal."/>}</SalesPanel>
 <SalesPanel title="Fuerza comercial" subtitle="Ranking por vendedor usando ID_VENDEDOR." className="ventasWidePanel"><div className="ventasTableWrap"><table className="ventasTable"><thead><tr><th>Vendedor</th><th>Ingreso</th><th>Ventas</th><th>Unidades</th><th>Clientes</th><th>Ticket</th><th>Participación</th></tr></thead><tbody>{(data.sellerBreakdown||[]).map(x=><tr key={x.name}><td>{x.name}</td><td>{money(x.revenue)}</td><td>{x.transactions}</td><td>{x.units||0}</td><td>{x.clients}</td><td>{money(x.avgTicket)}</td><td>{pct(x.share)}</td></tr>)}</tbody></table></div></SalesPanel>
 <SalesPanel title="Clientes con mayor ingreso" subtitle="Top clientes por ventas del periodo."><div className="ventasRankList full">{(data.clientBreakdown||[]).map((x,i)=><article key={x.id||x.name}><div><b style={{background:COLORS[i%COLORS.length]}}/><span>{x.name}</span></div><strong>{money(x.revenue)}</strong><small>{x.transactions} ventas · Ticket {money(x.avgTicket)} · {pct(x.share)}</small></article>)}</div></SalesPanel>
 <SalesPanel title="Insights comerciales" subtitle="Observaciones automáticas para toma de decisión."><div className="ventasInsights">{(data.insights||[]).map(x=><article className={x.type} key={x.title}><InsightIcon type={x.type}/><div><b>{x.title}</b><p>{x.text}</p></div></article>)}</div></SalesPanel>
 </div></div></main>;
}




// ----> LAST FUNCTIONAL AUG27/26 <----



// import { useEffect, useState } from 'react';
// import { AlertTriangle, ArrowDownCircle, ArrowUpCircle, BarChart3, LockKeyhole, ShoppingCart, Target, TrendingUp, Users } from 'lucide-react';
// import { Bar, BarChart, CartesianGrid, Cell, ComposedChart, Legend, Line, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
// import AppSidebar from './AppSidebar';
// import PeriodSelector from './PeriodSelector';
// import { getCasaMargotSales } from '../services/api';

// const COLORS=['#4d9661','#203b5c','#d9cbb8','#c7ced6','#8fa6b2','#9b7c55'];
// const money=(n=0)=>new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN',maximumFractionDigits:0}).format(Number(n)||0);const pct=(n=0)=>`${Math.round((Number(n)||0)*10)/10}%`;
// const fallback={period:{label:'Periodo'},meta:{years:[2026]},kpis:{},history:[],goalBars:[],categoryBreakdown:[],productBreakdown:[],channelBreakdown:[],sellerBreakdown:[],clientBreakdown:[],seasonality:{},availability:{},insights:[]};
// function growthClass(v=0){return Number(v)<0?'negative':'positive'}function growthIcon(v=0){return Number(v)<0?'↓':'↑'}
// function SalesKpi({icon:Icon,title,value,change,helper}){return <section className="ventasKpiCard"><div className="ventasKpiIcon"><Icon size={24}/></div><div><p>{title}</p><h2>{value}</h2>{change!==undefined&&change!==null&&<span className={growthClass(change)}>{growthIcon(change)} {pct(Math.abs(change||0))}</span>}{helper&&<small>{helper}</small>}</div></section>}
// function SalesPanel({title,subtitle,children,className=''}){return <section className={`ventasPanel ${className}`}><div className="ventasPanelHeader"><div><h3>{title}</h3>{subtitle&&<p>{subtitle}</p>}</div></div>{children}</section>}
// function InsightIcon({type}){if(type==='danger')return <ArrowDownCircle size={22}/>;if(type==='success')return <ArrowUpCircle size={22}/>;return <AlertTriangle size={22}/>}
// function Locked({title,text}){return <div className="unavailableState"><LockKeyhole size={22}/><div><b>{title}</b><p>{text}</p></div><span>Dato por activar</span></div>}

// export default function VentasScreen(){
//  const now=new Date();const [period,setPeriod]=useState({type:'month',index:now.getMonth()+1,year:now.getFullYear()});const [data,setData]=useState(fallback);const [loading,setLoading]=useState(true);
//  useEffect(()=>{setLoading(true);getCasaMargotSales(period).then(setData).catch(e=>{console.error('[VentasScreen]',e);setData(fallback)}).finally(()=>setLoading(false))},[period.type,period.index,period.year]);
//  const years=data.meta?.years?.length?data.meta.years:[period.year];const topCategory=data.seasonality?.topCategory;const topSeller=data.seasonality?.topSeller;
//  return <main className="appShell"><AppSidebar/><div className="dashboard ventasDashboard"><header className="topbar ventasTopbar"><div><p className="eyebrow">Casa Margot · Desempeño comercial</p><h1>Ventas</h1><p>Microscopio de ingresos, recurrencia, productos y fuerza comercial. {loading?'Actualizando datos…':''}</p></div><PeriodSelector {...period} label={data.period?.label||data.meta?.selectedMonthLabel} years={years} onChange={setPeriod}/></header>
//  <section className="ventasHero"><div><p>Ingreso total del periodo</p><h2>{money(data.kpis?.monthlySales)}</h2><span className={growthClass(data.kpis?.salesGrowth)}>{growthIcon(data.kpis?.salesGrowth)} {pct(Math.abs(data.kpis?.salesGrowth||0))} vs periodo anterior</span></div><div className="ventasHeroMeta"><p>Meta comercial</p>{data.availability?.goals?<><h3>{money(data.kpis?.monthlyGoal)}</h3></>:<Locked title="Meta aún no disponible" text="Cuando Casa Margot registre metas mensuales o por periodo, este bloque mostrará cumplimiento y brecha."/>}</div></section>
//  <div className="ventasKpiGrid"><SalesKpi icon={ShoppingCart} title="Número de ventas" value={data.kpis?.transactions||0} change={data.kpis?.transactionGrowth} helper="vs periodo anterior"/><SalesKpi icon={BarChart3} title="Ticket promedio" value={money(data.kpis?.avgTicket)} change={data.kpis?.avgTicketGrowth} helper="vs periodo anterior"/><SalesKpi icon={Users} title="Clientes únicos" value={data.kpis?.uniqueClients||0} helper={`${data.kpis?.newClients||0} nuevos · ${data.kpis?.recurrentClients||0} con recompra`}/><SalesKpi icon={TrendingUp} title="Venta acumulada año" value={money(data.kpis?.ytdSales)} change={data.kpis?.ytdGrowth} helper={`YTD ${period.year}`}/><SalesKpi icon={Target} title="Meta anual" value={data.availability?.goals?money(data.kpis?.annualGoal):'—'} helper={data.availability?.goals?'Seguimiento anual':'Dato por activar'}/></div>
//  <div className="ventasGrid">
//  <SalesPanel title="Histórico de ventas" subtitle="Evolución mensual y comparación contra el año anterior." className="ventasWidePanel"><ResponsiveContainer width="100%" height={310}><ComposedChart data={data.history||[]}><CartesianGrid vertical={false} strokeDasharray="4 6"/><XAxis dataKey="month"/><YAxis tickFormatter={v=>`$${Math.round(v/1000)}k`}/><Tooltip formatter={v=>money(v)}/><Legend/><Bar dataKey="sales" name="Ventas actuales" fill="#4d9661" radius={[8,8,0,0]}/><Line type="monotone" dataKey="lastYear" name="Año anterior" stroke="#aeb8c5" strokeDasharray="7 7" strokeWidth={2}/></ComposedChart></ResponsiveContainer></SalesPanel>
//  <SalesPanel title="Lectura rápida" subtitle="Temporadas, concentración y señales críticas."><div className="ventasQuickRead"><article><small>Mes más fuerte</small><b>{data.seasonality?.bestMonth||'Sin datos'}</b><p>Mayor ingreso mensual del año seleccionado.</p></article><article><small>Mes más bajo</small><b>{data.seasonality?.weakestMonth||'Sin datos'}</b><p>Periodo con menor ingreso registrado.</p></article><article><small>Categoría líder</small><b>{topCategory?.name||'Sin datos'}</b><p>{topCategory?`${pct(topCategory.share)} del ingreso del periodo.`:'Sin ventas registradas.'}</p></article><article><small>Vendedor líder</small><b>{topSeller?.name||'Sin datos'}</b><p>{topSeller?`${pct(topSeller.share)} del ingreso del periodo.`:'Sin vendedor registrado.'}</p></article></div></SalesPanel>
//  <SalesPanel title="Metas y brechas" subtitle="Ventas reales contra objetivo mensual.">{data.availability?.goals?<ResponsiveContainer width="100%" height={260}><BarChart data={data.goalBars||[]}><CartesianGrid vertical={false} strokeDasharray="4 6"/><XAxis dataKey="month"/><YAxis/><Tooltip/><Bar dataKey="goal" fill="#d9cbb8"/><Bar dataKey="sales" fill="#4d9661"/></BarChart></ResponsiveContainer>:<Locked title="Metas comerciales" text="Agrega una tabla de metas por mes/periodo para activar cumplimiento, brecha y avance anual."/>}</SalesPanel>
//  <SalesPanel title="Performance transaccional" subtitle="Volumen de ventas y ticket promedio por mes."><ResponsiveContainer width="100%" height={260}><ComposedChart data={data.history||[]}><CartesianGrid vertical={false} strokeDasharray="4 6"/><XAxis dataKey="month"/><YAxis yAxisId="left"/><YAxis yAxisId="right" orientation="right" tickFormatter={v=>`$${Math.round(v/1000)}k`}/><Tooltip formatter={(v,n)=>n==='Ticket promedio'?money(v):v}/><Legend/><Bar yAxisId="left" dataKey="transactions" name="Ventas" fill="#203b5c" radius={[8,8,0,0]}/><Line yAxisId="right" type="monotone" dataKey="avgTicket" name="Ticket promedio" stroke="#4d9661" strokeWidth={3}/></ComposedChart></ResponsiveContainer></SalesPanel>
//  <SalesPanel title="Segmentación por producto" subtitle="Qué familias venden más dentro del periodo."><div className="ventasSplitPanel"><ResponsiveContainer width="42%" height={240}><PieChart><Pie data={data.categoryBreakdown||[]} innerRadius={55} outerRadius={82} dataKey="revenue">{(data.categoryBreakdown||[]).map((_,i)=><Cell key={i} fill={COLORS[i%COLORS.length]}/>)}</Pie><Tooltip formatter={v=>money(v)}/></PieChart></ResponsiveContainer><div className="ventasRankList">{(data.categoryBreakdown||[]).map((x,i)=><article key={x.name}><div><b style={{background:COLORS[i%COLORS.length]}}/><span>{x.name}</span></div><strong>{money(x.revenue)}</strong><small>{pct(x.share)} · {x.transactions} ventas · Ticket {money(x.avgTicket)}</small></article>)}</div></div></SalesPanel>
//  <SalesPanel title="Segmentación por canal" subtitle="Dónde se origina el ingreso comercial.">{data.availability?.channels?<div className="ventasRankList full">{(data.channelBreakdown||[]).map((x,i)=><article key={x.name}><div><b style={{background:COLORS[i%COLORS.length]}}/><span>{x.name}</span></div><strong>{money(x.revenue)}</strong><div className="ventasProgress"><span style={{width:`${Math.min(x.share||0,100)}%`,background:COLORS[i%COLORS.length]}}/></div><small>{pct(x.share)} · {x.transactions} ventas · Ticket {money(x.avgTicket)}</small></article>)}</div>:<Locked title="Canal de origen" text="MEDIO_ORIGEN todavía no se registra de forma suficiente. Capturarlo activará venta, ticket y clientes por canal."/>}</SalesPanel>
//  <SalesPanel title="Fuerza comercial" subtitle="Ranking por vendedor usando ID_VENDEDOR." className="ventasWidePanel"><div className="ventasTableWrap"><table className="ventasTable"><thead><tr><th>Vendedor</th><th>Ingreso</th><th>Ventas</th><th>Unidades</th><th>Clientes</th><th>Ticket</th><th>Participación</th></tr></thead><tbody>{(data.sellerBreakdown||[]).map(x=><tr key={x.name}><td>{x.name}</td><td>{money(x.revenue)}</td><td>{x.transactions}</td><td>{x.units||0}</td><td>{x.clients}</td><td>{money(x.avgTicket)}</td><td>{pct(x.share)}</td></tr>)}</tbody></table></div></SalesPanel>
//  <SalesPanel title="Clientes con mayor ingreso" subtitle="Top clientes por ventas del periodo."><div className="ventasRankList full">{(data.clientBreakdown||[]).map((x,i)=><article key={x.id||x.name}><div><b style={{background:COLORS[i%COLORS.length]}}/><span>{x.name}</span></div><strong>{money(x.revenue)}</strong><small>{x.transactions} ventas · Ticket {money(x.avgTicket)} · {pct(x.share)}</small></article>)}</div></SalesPanel>
//  <SalesPanel title="Insights comerciales" subtitle="Observaciones automáticas para toma de decisión."><div className="ventasInsights">{(data.insights||[]).map(x=><article className={x.type} key={x.title}><InsightIcon type={x.type}/><div><b>{x.title}</b><p>{x.text}</p></div></article>)}</div></SalesPanel>
//  </div></div></main>;
// }
